const DARK_FONT_COLOR = '#c3c6d4';
const DARK_FONT_COLOR_CONTRAST = '#ffffff';
const DARK_FONT_COLOR_LV_1 = '#9699a6';

// SIDE_BAR
const DARK_SIDE_BAR_FONT_COLOR_CATALOG = '#d5d8df';
const DARK_SIDE_BAR_FONT_COLOR_CONTRAST = '#d5d6df';

export {
    DARK_FONT_COLOR,
    DARK_FONT_COLOR_CONTRAST,
    DARK_FONT_COLOR_LV_1,
    DARK_SIDE_BAR_FONT_COLOR_CATALOG,
    DARK_SIDE_BAR_FONT_COLOR_CONTRAST,
}