// LAYOUT CONSTANTS
const APP_BG_COLOR_LV_1_DARK = '#292e4b';

// COLORS
const BOARD_BG_COLOR_DARK = '#181b34';
const TOP_BOTTOM_COLUMN_COLOR = '#30324e';
const TASK_ELEMENT_BG_COLOR_DARK = '#2f324e';
const TASK_BORDER_COLOR_DARK = '#4b4e69';

const GROUP_ELEMENT_HOVER_COLOR = '#133774';

const ADD_TASK_BUTTON_BG_COLOR_DARK = '#0073ea';

// NAVBAR
const NAV_BAR_HEIGHT = 48;
const NAV_BAR_PADDING = '0 24px 0 4px';

const SIDE_BAR_WIDTH = 260;

export {
    APP_BG_COLOR_LV_1_DARK,
    NAV_BAR_HEIGHT, 
    NAV_BAR_PADDING, 
    SIDE_BAR_WIDTH, 
    BOARD_BG_COLOR_DARK,
    TOP_BOTTOM_COLUMN_COLOR,
    TASK_BORDER_COLOR_DARK,
    TASK_ELEMENT_BG_COLOR_DARK,
    ADD_TASK_BUTTON_BG_COLOR_DARK,
    GROUP_ELEMENT_HOVER_COLOR
};