// LAYOUT CONSTANTS

// COLORS
const BOARD_BG_COLOR_DARK = '#181b34';
const TASK_GROUP_BG_COLOR_DARK = '#30324e';

// NAVBAR
const NAV_BAR_HEIGHT = 48;
const NAV_BAR_PADDING = '0 24px 0 4px';

const SIDE_BAR_WIDTH = 260;

export { 
    NAV_BAR_HEIGHT, 
    NAV_BAR_PADDING, 
    SIDE_BAR_WIDTH, 
    BOARD_BG_COLOR_DARK,
    TASK_GROUP_BG_COLOR_DARK
};