const NORMAL_TASK_COLOR = '#2f324e';
const HOVERED_TASK_COLOR = '#33354b';
const TOP_BOTTOM_COLUMN_COLOR = '#30324e';
const SELECTED_TASK_COLOR = '#133774';

export {
    NORMAL_TASK_COLOR,
    HOVERED_TASK_COLOR,
    TOP_BOTTOM_COLUMN_COLOR,
    SELECTED_TASK_COLOR
}
